### ISSUE TITLE
[Idea] Oreminer.cs help

### ISSUE THREAD

**Issue by Muharrem652** [MCCTeam/Minecraft-Console-Client#2149]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

v1.19

### Describe your problem

`//MCCScript 1.0

MCC.LoadBot(new OreMiner());

//MCCScript Extensions

/// <summary>
/// This bot can mine blocks that auto-spawn at given locations
/// </summary>
public class OreMiner: ChatBot
{
    private bool miner = false;
    // === CONFIG - REPLACE BLOCK LOCATION x y z VALUES HERE ===
    List<Location> location = new List<Location>()
    {
        new Location(x, y, z),
        new Location(x2, y2, z2),
        new Location(x3, y3, z3),
        // Add more here
    };
    // === END OF CONFIG ===
    int index = 0;

    public override void Initialize()
    {
        LogToConsole("Bot enabled, please use /miner to start it");
	RegisterChatBotCommand("miner", "Automatic mining", "/miner start/stop", CommandHandler);
    }

    public override void Update()
    {
	if(miner == true)
	{
	    Material blockType = GetWorld().GetBlock(location[index]).Type;
	    switch (blockType)
	    {
		    //Adjust here block types to mine
		    case Material.Cobblestone:
		    case Material.Stone:
		    case Material.DiamondOre:
		    case Material.EmeraldOre:
		    case Material.GoldOre:
		    case Material.IronOre:
		    case Material.CoalOre:
		    case Material.LapisOre:
		    case Material.RedstoneOre:
		    case Material.NetherQuartzOre:
			    DigBlock(location[index]);
			    break;
	    }
	    index++;
	    if (index >= location.Count)
            index = 0;
	}
    }
    public string CommandHandler(string cmd, string[] args)
    {
        if (args.Length > 0)
        {
            switch (args[0])
            {
                case "stop":
		    miner = false;
		    return "Stop mining...";
	        case "start":
	    	    miner = true;
		    return "Start mining...";
            }
        }
        return "Usage: /miner start/stop";
    }
}`
break the blocks in the coordinates in order, if there is a block in the 1st coordinate, do not break the block in the 2nd cortinate (Sorry I'm translating with translate)

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

**Comment by Muharrem652** [comment]
can we save the bidet coordinates in a different file

**Comment by milutinke** [comment]
Can you please be more detailed and use correct grammar?
If you have issues with English, ask someone to translate it for you, since translation applications are not the best.

**Comment by Muharrem652** [comment]
1-yeni Konum(x,y,z),
2-yeni Konum(x2, y2, z2),
3-yeni Konum(x3, y3, z3),
1. pozisyonda blok varsa 2. pozisyonda blok kırmayınız.
1. bloğu kır ve 2. bloğu kır

**Comment by milutinke** [comment]
> 1-new Position(x,y,z), 2-new Position(x2, y2, z2), 3-new Position(x3, y3, z3), If there is a block in the 1st position, do not break the block in the 2nd position break the 1st block and break the 2nd block

For that you would have to modify the code of the chat bot.

**Comment by Muharrem652** [comment]
> > 1-new Position(x,y,z), 2-new Position(x2, y2, z2), 3-new Position(x3, y3, z3), If there is a block in the 1st position, do not break the block in the 2nd position break the 1st block and break the 2nd block
> 
> For that you would have to modify the code of the chat bot. Note that it is not officially supported, it's one of the community made ones and serves as an example.

if anyone can do this everyone can benefit

**Comment by BruceChenQAQ** [comment]
Try using this release. Added AutoDig ChatBot.
https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/toml-config

```toml
[ChatBot.AutoDig]
Enabled = true
Mode = "fixedpos"                           # "lookat", "fixedpos" or "both". Digging the block being looked at, the block in a fixed position, or the block that needs to be all met.
Locations = [
	{ x = -2620.0, y = 63.0, z = -1883.0 },
	{ x = -2620.0, y = 63.0, z = -1882.0 },
	{ x = -2620.0, y = 63.0, z = -1884.0 },
]                                           # The position of the blocks when using "fixedpos" or "both" mode.
Location_Order = "index"                 # "distance" or "index", When using the "fixedpos" mode, the blocks are determined by distance to the player, or by the order in the list.
Auto_Start_Delay = 3.0                      # How many seconds to wait after entering the game to start digging automatically, set to -1 to disable automatic start.
Dig_Timeout = 10.0                          # Mining a block for more than "Dig_Timeout" seconds will be considered a timeout.
Log_Block_Dig = true                        # Whether to output logs when digging blocks.
List_Type = "whitelist"                     # Wether to treat the blocks list as a "whitelist" or as a "blacklist".
Blocks = [ "Cobblestone", "Stone", ]
```
