### ISSUE TITLE
[Feature] Dig start/stop

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2250]
Now MCC is know where is bot and which block it looking at.
So, I think it is a good idea to add a /dig start/stop command, which start digging blocks looked by bot.
Also it is very useful for people who use MCC like cobblestone miner on Skyblock.

**Comment by deosync** [comment]
Есть чат-бот на это

**Comment by Sergapr** [comment]
> Есть чат-бот на это

Попробуй в следующий раз писать на английском, чтоб если у кого-то будет такая же проблема он без труда понял тебя.
Где можно найти подобного чат-бота?

**Comment by Sergapr** [comment]
Мне нужен именно тот что будет ломать блоки на которые смотрит бот. Не те что зависят от координат бота и он ломает те что сверху, сбоку и т.Д

**Comment by BruceChenQAQ** [comment]
In the current version you can keep mining the block you are looking at by using the `ScriptScheduler`.
However, the interval should be set to the maximum possible for mining those blocks.

```toml
[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "digging"
Trigger_On_First_Login = false
Trigger_On_Login = false
Trigger_On_Times = { Enable = false, Times = [ ] }
Trigger_On_Interval = { Enable = true, MinTime = 2, MaxTime = 2 }
Action = "dig"
```
