### ISSUE TITLE
Endless digging from multiple accounts

### ISSUE THREAD

**Issue by username902** [MCCTeam/Minecraft-Console-Client#2308]
Hello, I want to make it so that I can dig 5 blocks on several accounts without delay, but I can’t do it, please help me, how to make a code so that the console digs 5 blocks endlessly from several accounts at once

**Comment by BruceChenQAQ** [comment]
You can use [AutoDig ChatBot](https://mccteam.github.io/guide/chat-bots.html#auto-dig).
The account that MCC will log into can be set via parameters such as `MCC.exe UserName Password`.

```toml
[Main.Advanced]
TerrainAndMovements = true

[ChatBot.AutoDig]
Enabled = true
Mode = "fixedpos"
Locations = [
	{ x = 123.5, y = 64.0, z = 234.5 },
	{ x = 124.5, y = 63.0, z = 235.5 },
	{ x = 124.5, y = 63.0, z = 235.5 },
	{ x = 124.5, y = 63.0, z = 235.5 },
	{ x = 124.5, y = 63.0, z = 235.5 },
]
List_Type = "blacklist"
Blocks = [ ]
```
