### ISSUE TITLE
Cant install at all

### ISSUE THREAD

**Issue by CoomInPickle** [MCCTeam/Minecraft-Console-Client#2579]
hey, im trying to install MCC with portainer in a docker container. the issue the docker-compose.yml doesnt work and gives me an error:
```
failed to deploy a stack: MCC Pulling MCC Error Error response from daemon: pull access denied for minecraft-console-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
``` 

also when i try to install it as told in the documentation it also results in an error. but i would prefer to use the docker compose.

is there any way i can fix this?

also, idk how to add the question label

**Comment by ReinforceZwei** [comment]
Post your docker-compose.yml

**Comment by CoomInPickle** [comment]
```yml
version: '2'

services:
  MCC:
    image: 'minecraft-console-client:latest'
    container_name: 'MinecraftConsoleClient'
    # You could also comment out the volumes section if you don't want to mount the volume. That is up to you. If you do so it's harder to edit the .ini file if thats something you want to do.
    volumes:
    - '/home/docker/mcc/data:/opt/data'
    ```
