### ISSUE TITLE
I want to script or code

### ISSUE THREAD

**Issue by xDarkLife55** [MCCTeam/Minecraft-Console-Client#2792]
I want to per two minute autobot send message "/repair hand". How can I do that ?

**Comment by milutinke** [comment]
Use Script Scheduler, I've mentioned it in #2790 .

You can add the following task to the ScriptScheduler:
```toml
[[ChatBot.ScriptScheduler.TaskList]]
    Task_Name = "Repair Task"
    Trigger_On_First_Login = false
    Trigger_On_Login = false
    Trigger_On_Times = { Enable = false, Times = [ 14:00:00, ] }
    Trigger_On_Interval = { Enable = true, MinTime = 2.0, MaxTime = 2.0 }
    Action = "send /repair hand"
```
